name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Install Goreleaser
      run: |
        curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh -s -- -b $(go env GOPATH)/bin v0.184.0

    - name: Run Goreleaser
      run: |
        $(go env GOPATH)/bin/goreleaser release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}